webtalk_init -webtalk_dir D:/Desktop/CPU_3/CPU_3.sim/sim_1/behav/xsim/xsim.dir/sim_1_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu May 20 19:53:51 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3c2eafaf-6adf-4dc8-adb5-7d449c283b5a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2fd418735e444d6b82ff06760579ef25" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "108" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "11 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.33_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "10532_KB" -context "xsim\\usage"
webtalk_transmit -clientid 523870934 -regid "" -xml D:/Desktop/CPU_3/CPU_3.sim/sim_1/behav/xsim/xsim.dir/sim_1_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Desktop/CPU_3/CPU_3.sim/sim_1/behav/xsim/xsim.dir/sim_1_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Desktop/CPU_3/CPU_3.sim/sim_1/behav/xsim/xsim.dir/sim_1_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
